config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

  # get 'tasks', to: 'tasks#index'
  # get 'tasks/:id', to: 'tasks#show'
  # get 'tasks/new', to: 'tasks#new'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/:id/edit', to: 'tasks#edit'
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
# Afficher les tâches
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

# Créer une tâche
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    @task.save
  end

# Editer une tâche
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(params[:task])
    @task.save
  end

# Sup une tâche
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name, "Enter a name" %>
  <%= f.text_field :name %>

  <%= f.label :content, "Enter a content" %>
  <%= f.text_field :content %>

  <%= f.label :date %>
  <%= f.number_field :date %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<!--Afficher toutes les tâches -->
<% @tasks.each do |task| %>
  <h2> <%= task.name %> </h2>
  <p> <%= task.content %> </p>
  <p> <%= task.date %> </p>
<!--Link to its show view -->
<%= link_to "Show", task_path(task) %>
<!--Link to its edit view -->
<%= link_to "Edit", edit_task_path(task) %>
<!--Link to its delete action -->
<%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<% end %>

app/views/tasks/show.html.erb
<!--Afficher une tâche -->
<h1> <% @task.name %> </h1>
<p> <%= @task.content %> </p>
<p> <%= @task.date %> </p>

<%= link_to "Back to list", tasks_path %>